### ISSUE TITLE
No "cov" or "logs" dir

### ISSUE THREAD

**Issue by haomingzhang** [30x/apidCRUD#2]
The default coverage and log dirs are "./cov" and "./logs", which are not in the repo.
If you run unit-test for the first time, before "make install", it will fail due to missing dirs.
You may add it in Makefile for "unit-test", since users are not assumed to run "make install" before "make unit-test". Or you can just ask them to in README.md
Also, I suggest to add "glide up" to README.md

**Comment by dfong** [comment]
good point.
